project:
  type: website
  output-dir: docs

website:
  title: "Songting Chen"
  sidebar:
    style: "docked"
    background: primary
    logo: songting_chen.jpg
    contents:
      - text: "INTRODUCTION"
        href: index.qmd#intro
      - text: "EDUCATION"
        href: index.qmd#education
      - text: "IT SKILLS"
        href: index.qmd#skills
      - text: "EXPERIENCE"
        href: index.qmd#experience
      - text: "PROJECTS"
        href: index.qmd#projects
      - text: "INTERESTS"
        href: index.qmd#interests

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true