project:
  type: website
  output-dir: docs

website:
  title: "Songting Chen"
  navbar:
    logo: songting_chen.jpg
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: CV
        href: CV.pdf
    right:
      - icon: github
        href: https://github.com/songtingchen-web
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css 
    toc: false